#Hands on pratice :Linear algebra for AI

#Working with scalar and vector

In [2]:
import numpy as np

scalar=9
print(scalar)

vector=np.array([3,6,8,45,39])
print(vector)

scaled_vector=scalar*vector
print(scaled_vector)

9
[ 3  6  8 45 39]
[ 27  54  72 405 351]


#Adding and Subtracting vector

In [5]:
vector1=np.array([3,6,8,45,39])
print(vector)

vector2=np.array([3,6,8,45,39])
print(vector)

add=vector1+vector2
print(add)

sub=(vector1-vector2)
print(sub)

[ 3  6  8 45 39]
[ 6 12 16 90 78]
[0 0 0 0 0]


#HW

In [ ]:
vector1=np.array([4,5,6])
print(3*vector1)

In [16]:
v1=np.array([10,20])
v2=np.array([30,40])

addition=v1+v2
print(addition)

subtract=v1-v2
print(subtract)


[40 60]
[-20 -20]


In [21]:
matrix1=np.array([[1,0],[0,1]])
matrix2=np.array([[2,3],[5,6]])


print(np.dot(matrix1,matrix2))


[[2 3]
 [5 6]]


#MATRIX CREATION AND SIMPLE OPERATION

In [19]:
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix1)

matrix2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix2)

add=matrix1+matrix2
print(add)

sub=matrix1-matrix2
print(sub)

print(np.dot(matrix1,matrix2))#matrix multiplication

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [32]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

c=a[0,0]*b[0,0]
d=a[0,1]*b[1,0]
x=c+d
print(x)
e=a[0,0]*b[0,1]
f=a[0,1]*b[1,1]
y=e+f
print(y)

g=a[1,0]*b[0,0]
h=a[1,1]*b[1,0]
z=g+h
print(z)
i=a[1,0]*b[0,1]
j=a[1,1]*b[1,1]
w=i+j
print(w)



matrix=np.array([[x,y],[z,w]])
print(matrix)

print(np.dot(a,b))

19
22
43
50
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [33]:
v1=np.array([7,8,9])
result=2*v1
print(result)

[14 16 18]


In [34]:
v1=np.array([3,4])
v2=np.array([1,2])

addition=v1+v2
print(addition)

subtract=v1-v2
print(subtract)

[4 6]
[2 2]


In [38]:
a=np.array([[0,1],[2,3]])
b=np.array([[4,5],[6,7]])

result=a+b
print(result)

[[ 4  6]
 [ 8 10]]


In [39]:
a=np.array([[2,1],[0,3]])
b=np.array([[1,2],[3,4]])

print(np.dot(a,b))

[[ 5  8]
 [ 9 12]]


In [43]:
a=np.array([[5,10,15],[20,25,30]])
print(a.T)

#it can't be identity because there should be same no of rows and col
#b =np.linalg.inv(a)
#print(a.b)

[[ 5 20]
 [10 25]
 [15 30]]


LinAlgError: Last 2 dimensions of the array must be square