#DAY 5

CREATING A NUMPY ARRAY AND ITS ATTRIBUTES

In [4]:
import numpy as np
array=np.array([1,2,3,4,5])
print(array)

#0-D array
zeroarray=np.array(10)
print(zeroarray)

#1-D array
onedarray=np.array([1,2,3,4,5])
print(onedarray)

#2-D array
twodarray=np.array([[1,2,3],[4,5,6]])
print(twodarray)

#3-D array
threedarray=np.array([[1,2,3],
                        [4,5,6],
                         [7,8,9]])
print(threedarray)




[1 2 3 4 5]
10
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#create attribute
import numpy as np

array=np.array([[1,2,3],[7,4,5]])
print(array)
print(array.ndim)
print(array.shape)
print(array.dtype)
print(array.size)


[[1 2 3]
 [7 4 5]]
2
(2, 3)
int64
6


In [9]:
#ACCESSING AND MANIPULATING ARRAY ELEMENTS

a=np.array([1,2,3,4,5])
print(a[4])

print(a[-1])#negative indexing




5
5


In [12]:
#for 2D array
two=np.array([[1,2,3],[4,5,6]])
print(two[1,2])
print(two[0,2])

6
3


In [14]:
#3-D Array
three=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three[0,1,2])
print(three[1,0,0])

6
7


In [16]:
 #SLICING ARRAY

three_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]);
print(three_arr[::-1])


[[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [22]:
array=np.array([1,2,3,4,5,6,7,8,9])
print(array[0:4])
print(array[::-1])
print(array[0:9:2])
print(array[1:9:2])

[1 2 3 4]
[9 8 7 6 5 4 3 2 1]
[1 3 5 7 9]
[2 4 6 8]


In [24]:
array=np.array([[1,2,3],[4,5,6]])
print(array[0,1:3])

[2 3]


In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [28]:
array=np.array([7,14,21,28])
print(array)

[ 7 14 21 28]


In [35]:
a=np.array([[5,10,15],[20,25,30]])
print(a.shape)
print(a.ndim)

(2, 3)
2


In [40]:
a=np.zeros((2,3))
print(a)
b=np.arange(0,12,3)
print(b)


[[0. 0. 0.]
 [0. 0. 0.]]
[0 3 6 9]


In [41]:
arr=np.array([2,3,6,8])
print(arr*3)

[ 6  9 18 24]


In [43]:
array=np.array([1,3,5,7,9,11])
print(array[2])
print(array[1:3])

5
[3 5]


In [45]:
arr=np.random.randint(0,10,size=(3,3))
print(arr)

[[9 8 8]
 [2 0 7]
 [0 7 0]]


In [52]:
a=np.array([2,4,6,8])
b=np.array([1,3,5,7])
print(a+b)




[ 3  7 11 15]


In [54]:
d=np.array([2,4,6,8])
c=np.array([1,3,5,7])
print(d*c)

[ 2 12 30 56]


In [59]:
arr=np.ones((4,3))

print(arr)

r=arr.reshape(3,4)

print(r)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [66]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
a=array[1,0:]
mean=np.mean(a)
print(mean)
print(a)

reshape=array.reshape(-1)
print(reshape)


5.0
[4 5 6]
[1 2 3 4 5 6 7 8 9]


In [72]:
array=np.array([10,20,30,40,50,60])
m=array > 30
print(m)
print(array)

[False False False  True  True  True]
[10 20 30 40 50 60]
